test comments

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,27 +6,24 @@ on:
       - main
   repository_dispatch:
     types: [ipp-merge-pr]
-  workflow_dispatch:
-
-run-name: >-
-  ${{ github.event_name == 'repository_dispatch' && format('Pull Request ({0})', github.event.client_payload.pr_name) 
-      || github.event_name == 'workflow_dispatch' && format('Start API Tests (Manual)') 
-      || format('Start API Tests') }}
 
 jobs:
   pr-merge:
+    if: github.event_name == 'repository_dispatch' && github.event.action == 'ipp-merge-pr'
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4.2.2
 
-      - name: Dump GitHub context
-        env:
-          GITHUB_CONTEXT: ${{ toJSON(github) }}
-        run: echo "$GITHUB_CONTEXT"
+      - name: Do API Tests (Fail)
+        run: |
+          echo "Failed API Tests"
+          exit 1
 
-      - name: Print PR Merge Event
-        if: github.event_name == 'repository_dispatch'
-        run: echo "PR Title ${{ github.event.client_payload.pr_name }} and ${{ github.event.name }}"
-
-
+      - name: Post Comment on Jira
+        uses: ./.github/workflows/actions/jira-commenter
+        with:
+          reports: '{"name": "Example Report","report-url": "https://example.com/report"}.'
+          jira_user_api_token: 'api-token'
+          ticket: 'TEST-123'
+          jira_user_email: 'username'
